name: Build packages
on: [workflow_dispatch,push]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Get the code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.REPO_TOKEN }}

      - name: install autobuild
         run: pip3 install git+https://github.com/Nicky-D/autobuild@main_nd

      - name: Build app packages
        run: ./build.sh

      - name: Build tarball
        run: ./create_sysroot.sh

      - name: publish ${{ runner.os }} artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-artifacts.zip
          path: _results/*

