name: Build packages
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Get the code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.REPO_TOKEN }}

      - name: debug
        run: ls -l


